/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vut.gui;

/**
 *
 * @author Jordan M
 */
public class Java_Calculator extends javax.swing.JDialog
{

    public static int firstnumb = 0;
    public static int secondnumb = 0;
    public static String opperator = "none";
    public static Boolean is_blocked = false;

    /**
     * Creates new form EmployeeApplication
     */
    public Java_Calculator(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnOne = new javax.swing.JButton();
        txtTextBox = new javax.swing.JTextField();
        btntwo = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnAnswer = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java_Calculator");

        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOneActionPerformed(evt);
            }
        });

        txtTextBox.setColumns(30);
        txtTextBox.setText("0");

        btntwo.setText("2");
        btntwo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btntwoActionPerformed(evt);
            }
        });

        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSixActionPerformed(evt);
            }
        });

        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnThreeActionPerformed(evt);
            }
        });

        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEightActionPerformed(evt);
            }
        });

        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSevenActionPerformed(evt);
            }
        });

        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNineActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMinusActionPerformed(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        btnMultiply.setText("X");
        btnMultiply.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnAnswer.setText("Answer");
        btnAnswer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnswerActionPerformed(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDivideActionPerformed(evt);
            }
        });

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnZeroActionPerformed(evt);
            }
        });

        btnBackspace.setText("Clear");
        btnBackspace.setToolTipText("");
        btnBackspace.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntwo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThree))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnFour)
                                        .addComponent(btnSeven))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnFive)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSix))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnEight)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnNine))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntwo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOneActionPerformed
    {//GEN-HEADEREND:event_btnOneActionPerformed
        // numb1:
        String button_Text = btnOne.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btntwoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btntwoActionPerformed
    {//GEN-HEADEREND:event_btntwoActionPerformed
        // numb2:
        String button_Text = btntwo.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btntwoActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFourActionPerformed
    {//GEN-HEADEREND:event_btnFourActionPerformed
        // numb4:
        String button_Text = btnFour.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFiveActionPerformed
    {//GEN-HEADEREND:event_btnFiveActionPerformed
        // numb5:
        String button_Text = btnFive.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSixActionPerformed
    {//GEN-HEADEREND:event_btnSixActionPerformed
        // numb6:
        String button_Text = btnSix.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnThreeActionPerformed
    {//GEN-HEADEREND:event_btnThreeActionPerformed
        // numb3:
        String button_Text = btnThree.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEightActionPerformed
    {//GEN-HEADEREND:event_btnEightActionPerformed
        // numb8:
        String button_Text = btnEight.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSevenActionPerformed
    {//GEN-HEADEREND:event_btnSevenActionPerformed
        // numb7:
        String button_Text = btnSeven.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNineActionPerformed
    {//GEN-HEADEREND:event_btnNineActionPerformed
        // numb9:
        String button_Text = btnNine.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMinusActionPerformed
    {//GEN-HEADEREND:event_btnMinusActionPerformed
        // TODO add your handling code here:
        is_blocked = false;
        opperator = "minus";
        get_firstnumb();
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
    {//GEN-HEADEREND:event_btnAddActionPerformed
        // TODO add your handling code here:
        is_blocked = false;
        opperator = "Add";
        get_firstnumb();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMultiplyActionPerformed
    {//GEN-HEADEREND:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        is_blocked = false;
        opperator = "multiply";
        get_firstnumb();
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAnswerActionPerformed
    {//GEN-HEADEREND:event_btnAnswerActionPerformed
        // TODO add your handling code here:
        is_blocked = get_Answer(is_blocked);
    }//GEN-LAST:event_btnAnswerActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDivideActionPerformed
    {//GEN-HEADEREND:event_btnDivideActionPerformed
        // TODO add your handling code here:
        is_blocked = false;
        opperator = "divide";
        get_firstnumb();
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnZeroActionPerformed
    {//GEN-HEADEREND:event_btnZeroActionPerformed
        // numb0:
        String button_Text = btnZero.getText();
        put_text_on_textBox(button_Text);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackspaceActionPerformed
    {//GEN-HEADEREND:event_btnBackspaceActionPerformed
        // TODO add your handling code here:
    firstnumb = 0;
    secondnumb = 0;
    opperator = "none";
    txtTextBox.setText("0");
    is_blocked = false;
    }//GEN-LAST:event_btnBackspaceActionPerformed

        /**
         * @param args the command line arguments
         */
        private void put_text_on_textBox(String button_Text)
    {
        String str1 = txtTextBox.getText();
        if (str1.equals("0"))
        {
            txtTextBox.setText("");
        }
        txtTextBox.setText(txtTextBox.getText() + button_Text);
    }

    public void get_firstnumb()
    {
        firstnumb = Integer.parseInt(txtTextBox.getText());
        txtTextBox.setText("");
    }

    public boolean get_Answer(boolean Block)
    {
        if (txtTextBox.getText().length() > 0 && Block != true)
        {
            Block = true;
            secondnumb = Integer.parseInt(txtTextBox.getText());
            txtTextBox.setText("");
            switch (opperator)
            {
                case "divide": 
                    txtTextBox.setText(Integer.toString(firstnumb / secondnumb));
                    break;
                case "multiply":
                    txtTextBox.setText(Integer.toString(firstnumb * secondnumb));
                    break;
                case "Add":
                    txtTextBox.setText(Integer.toString(firstnumb + secondnumb));
                    break;
                case "minus":
                    txtTextBox.setText(Integer.toString(firstnumb - secondnumb));
                    break;
            }
        }
        return Block;
    }
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Java_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Java_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Java_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Java_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Java_Calculator dialog = new Java_Calculator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAnswer;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btntwo;
    private javax.swing.JTextField txtTextBox;
    // End of variables declaration//GEN-END:variables

}
